#
# Module manifest for module 'PasswordGenerator'
# Generated by: Timothy Small
# Generated on: 8/26/2021
#

@{
    RootModule        = "PasswordGenerator.dll"
    ModuleVersion     = "2021.8.1"
    GUID              = "afebc039-b2cf-482b-8e1d-1651de109d65"
    Author            = "Timothy Small"
    CompanyName       = "Smalls.Online"
    Copyright         = "2021"
    Description       = "Create randomly generated passwords with PowerShell."

    # CompatiblePSEditions = @()
    # PowerShellVersion = ""
    # PowerShellHostName = ""
    # PowerShellHostVersion = ""
    # DotNetFrameworkVersion = ""
    # ClrVersion = ""
    # ProcessorArchitecture = ""

    # RequiredModules = @()
    # RequiredAssemblies = @()
    # ScriptsToProcess = @()
    # TypesToProcess = @()
    # FormatsToProcess = @()
    # NestedModules = @()

    FunctionsToExport = @()
    CmdletsToExport   = @(
        "New-RandomPassword",
        "New-RandomNumber"
    )
    VariablesToExport = "*"
    AliasesToExport   = @()
    # DscResourcesToExport = @()

    # ModuleList = @()
    FileList          = @(
        "PasswordGenerator.dll",
        "PasswordGenerator.psd1"
    )

    PrivateData       = @{
        PSData = @{
            Tags = @(
                "password-generator",
                "passwords"
            )

            LicenseUri = "https://raw.githubusercontent.com/Smalls1652/pwsh.PasswordGenerator/main/LICENSE"
            RequireLicenseAcceptance = $false

            ProjectUri = "https://github.com/Smalls1652/pwsh.PasswordGenerator"
            # IconUri = ""
            # ReleaseNotes = ""
            # Prerelease = ""
            # ExternalModuleDependencies = @()

        }
    }
    # HelpInfoURI = ""
    # DefaultCommandPrefix = ""
}

